version: '{build}'

environment:
  project_name: util-cpp-common
  project_test_name: util-cpp-common-test
  project_test_location: .\%CONFIGURATION%\%project_test_name%.dll

image:
  - Visual Studio 2013

configuration:
  - Release

build:
  project: .\%project_name%.sln

test_script:
  - vstest.console.exe /logger:Appveyor "%project_test_location%"
