version: '{build}'

environment:
  project_name: util-cpp-common
  project_test_name: util-cpp-common-test
  project_test_location: .\src\test\%CONFIGURATION%\%project_core_test_name%.dll

image:
  - Visual Studio 2013

configuration:
  - Release

build:
  project: .\%project_name%.sln

before_build:
  - choco install opencover.portable
  - choco install codecov

test_script:
  - OpenCover.Console.exe -register:user -target:"vstest.console" -targetargs:"/logger:Appveyor ""%project_test_location%" -filter:"+[%project_name%*]* -[%project_test_name%*]*" -output:".\coverage.xml" -returntargetcode
  - codecov -f "coverage.xml"
